-- Seeds: capitais e principais cidades de todos os estados brasileiros
-- Idempotente: não duplica cidades já existentes no banco.

INSERT INTO cidade (cidade, estado_id)
SELECT v.nome, e.id
FROM (VALUES
    -- Acre
    ('Rio Branco',         'Acre'),
    ('Cruzeiro do Sul',    'Acre'),
    ('Sena Madureira',     'Acre'),
    ('Tarauacá',           'Acre'),
    -- Alagoas
    ('Maceió',             'Alagoas'),
    ('Arapiraca',          'Alagoas'),
    ('Palmeira dos Índios','Alagoas'),
    ('Rio Largo',          'Alagoas'),
    ('União dos Palmares', 'Alagoas'),
    -- Amazonas
    ('Manaus',             'Amazonas'),
    ('Parintins',          'Amazonas'),
    ('Itacoatiara',        'Amazonas'),
    ('Manacapuru',         'Amazonas'),
    ('Coari',              'Amazonas'),
    -- Amapá
    ('Macapá',             'Amapá'),
    ('Santana',            'Amapá'),
    ('Laranjal do Jari',   'Amapá'),
    ('Oiapoque',           'Amapá'),
    -- Bahia
    ('Salvador',           'Bahia'),
    ('Feira de Santana',   'Bahia'),
    ('Vitória da Conquista','Bahia'),
    ('Camaçari',           'Bahia'),
    ('Itabuna',            'Bahia'),
    ('Juazeiro',           'Bahia'),
    ('Lauro de Freitas',   'Bahia'),
    ('Ilhéus',             'Bahia'),
    ('Jequié',             'Bahia'),
    -- Ceará
    ('Fortaleza',          'Ceará'),
    ('Caucaia',            'Ceará'),
    ('Juazeiro do Norte',  'Ceará'),
    ('Maracanaú',          'Ceará'),
    ('Sobral',             'Ceará'),
    ('Crato',              'Ceará'),
    ('Itapipoca',          'Ceará'),
    -- Distrito Federal
    ('Brasília',           'Distrito Federal'),
    -- Espírito Santo
    ('Vitória',            'Espírito Santo'),
    ('Vila Velha',         'Espírito Santo'),
    ('Cariacica',          'Espírito Santo'),
    ('Serra',              'Espírito Santo'),
    ('Cachoeiro de Itapemirim','Espírito Santo'),
    ('Linhares',           'Espírito Santo'),
    -- Goiás
    ('Goiânia',            'Goiás'),
    ('Aparecida de Goiânia','Goiás'),
    ('Anápolis',           'Goiás'),
    ('Rio Verde',          'Goiás'),
    ('Luziânia',           'Goiás'),
    ('Águas Lindas de Goiás','Goiás'),
    ('Trindade',           'Goiás'),
    -- Maranhão
    ('São Luís',           'Maranhão'),
    ('Imperatriz',         'Maranhão'),
    ('São José de Ribamar','Maranhão'),
    ('Timon',              'Maranhão'),
    ('Caxias',             'Maranhão'),
    ('Codó',               'Maranhão'),
    -- Mato Grosso
    ('Cuiabá',             'Mato Grosso'),
    ('Várzea Grande',      'Mato Grosso'),
    ('Rondonópolis',       'Mato Grosso'),
    ('Sinop',              'Mato Grosso'),
    ('Tangará da Serra',   'Mato Grosso'),
    ('Sorriso',            'Mato Grosso'),
    -- Mato Grosso do Sul
    ('Campo Grande',       'Mato Grosso do Sul'),
    ('Dourados',           'Mato Grosso do Sul'),
    ('Três Lagoas',        'Mato Grosso do Sul'),
    ('Corumbá',            'Mato Grosso do Sul'),
    ('Ponta Porã',         'Mato Grosso do Sul'),
    -- Minas Gerais
    ('Belo Horizonte',     'Minas Gerais'),
    ('Uberlândia',         'Minas Gerais'),
    ('Contagem',           'Minas Gerais'),
    ('Juiz de Fora',       'Minas Gerais'),
    ('Betim',              'Minas Gerais'),
    ('Montes Claros',      'Minas Gerais'),
    ('Ribeirão das Neves', 'Minas Gerais'),
    ('Uberaba',            'Minas Gerais'),
    ('Governador Valadares','Minas Gerais'),
    ('Ipatinga',           'Minas Gerais'),
    ('Sete Lagoas',        'Minas Gerais'),
    -- Pará
    ('Belém',              'Pará'),
    ('Ananindeua',         'Pará'),
    ('Santarém',           'Pará'),
    ('Marabá',             'Pará'),
    ('Castanhal',          'Pará'),
    ('Parauapebas',        'Pará'),
    -- Paraíba
    ('João Pessoa',        'Paraíba'),
    ('Campina Grande',     'Paraíba'),
    ('Santa Rita',         'Paraíba'),
    ('Patos',              'Paraíba'),
    ('Bayeux',             'Paraíba'),
    -- Paraná
    ('Curitiba',           'Paraná'),
    ('Londrina',           'Paraná'),
    ('Maringá',            'Paraná'),
    ('Ponta Grossa',       'Paraná'),
    ('Cascavel',           'Paraná'),
    ('São José dos Pinhais','Paraná'),
    ('Foz do Iguaçu',      'Paraná'),
    ('Colombo',            'Paraná'),
    ('Guarapuava',         'Paraná'),
    ('Paranaguá',          'Paraná'),
    -- Pernambuco
    ('Recife',             'Pernambuco'),
    ('Caruaru',            'Pernambuco'),
    ('Olinda',             'Pernambuco'),
    ('Petrolina',          'Pernambuco'),
    ('Paulista',           'Pernambuco'),
    ('Jaboatão dos Guararapes','Pernambuco'),
    ('Cabo de Santo Agostinho','Pernambuco'),
    -- Piauí
    ('Teresina',           'Piauí'),
    ('Parnaíba',           'Piauí'),
    ('Picos',              'Piauí'),
    ('Floriano',           'Piauí'),
    ('Campo Maior',        'Piauí'),
    -- Rio de Janeiro
    ('Rio de Janeiro',     'Rio de Janeiro'),
    ('São Gonçalo',        'Rio de Janeiro'),
    ('Duque de Caxias',    'Rio de Janeiro'),
    ('Nova Iguaçu',        'Rio de Janeiro'),
    ('Niterói',            'Rio de Janeiro'),
    ('Belford Roxo',       'Rio de Janeiro'),
    ('Campos dos Goytacazes','Rio de Janeiro'),
    ('São João de Meriti', 'Rio de Janeiro'),
    ('Petrópolis',         'Rio de Janeiro'),
    ('Volta Redonda',      'Rio de Janeiro'),
    -- Rio Grande do Norte
    ('Natal',              'Rio Grande do Norte'),
    ('Mossoró',            'Rio Grande do Norte'),
    ('Parnamirim',         'Rio Grande do Norte'),
    ('São Gonçalo do Amarante','Rio Grande do Norte'),
    ('Caicó',              'Rio Grande do Norte'),
    -- Rio Grande do Sul
    ('Porto Alegre',       'Rio Grande do Sul'),
    ('Caxias do Sul',      'Rio Grande do Sul'),
    ('Canoas',             'Rio Grande do Sul'),
    ('Pelotas',            'Rio Grande do Sul'),
    ('Santa Maria',        'Rio Grande do Sul'),
    ('Gravataí',           'Rio Grande do Sul'),
    ('Novo Hamburgo',      'Rio Grande do Sul'),
    ('São Leopoldo',       'Rio Grande do Sul'),
    ('Viamão',             'Rio Grande do Sul'),
    ('Passo Fundo',        'Rio Grande do Sul'),
    -- Rondônia
    ('Porto Velho',        'Rondônia'),
    ('Ji-Paraná',          'Rondônia'),
    ('Ariquemes',          'Rondônia'),
    ('Vilhena',            'Rondônia'),
    ('Cacoal',             'Rondônia'),
    -- Roraima
    ('Boa Vista',          'Roraima'),
    ('Rorainópolis',       'Roraima'),
    ('Caracaraí',          'Roraima'),
    -- Santa Catarina (complemento — as 10 originais já existem no seeds.sql)
    ('Balneário Camboriú', 'Santa Catarina'),
    ('Tubarão',            'Santa Catarina'),
    ('Caçador',            'Santa Catarina'),
    ('Biguaçu',            'Santa Catarina'),
    ('Içara',              'Santa Catarina'),
    ('Navegantes',         'Santa Catarina'),
    ('Camboriú',           'Santa Catarina'),
    ('São Bento do Sul',   'Santa Catarina'),
    -- São Paulo
    ('São Paulo',          'São Paulo'),
    ('Guarulhos',          'São Paulo'),
    ('Campinas',           'São Paulo'),
    ('São Bernardo do Campo','São Paulo'),
    ('São José dos Campos','São Paulo'),
    ('Ribeirão Preto',     'São Paulo'),
    ('Santo André',        'São Paulo'),
    ('Osasco',             'São Paulo'),
    ('Sorocaba',           'São Paulo'),
    ('São José do Rio Preto','São Paulo'),
    ('Mogi das Cruzes',    'São Paulo'),
    ('Santos',             'São Paulo'),
    ('Jundiaí',            'São Paulo'),
    ('Piracicaba',         'São Paulo'),
    ('Bauru',              'São Paulo'),
    ('Franca',             'São Paulo'),
    ('Diadema',            'São Paulo'),
    ('Carapicuíba',        'São Paulo'),
    ('Limeira',            'São Paulo'),
    ('São Vicente',        'São Paulo'),
    -- Sergipe
    ('Aracaju',            'Sergipe'),
    ('Lagarto',            'Sergipe'),
    ('Nossa Senhora do Socorro','Sergipe'),
    ('São Cristóvão',      'Sergipe'),
    ('Itabaiana',          'Sergipe'),
    -- Tocantins
    ('Palmas',             'Tocantins'),
    ('Araguaína',          'Tocantins'),
    ('Gurupi',             'Tocantins'),
    ('Porto Nacional',     'Tocantins'),
    ('Paraíso do Tocantins','Tocantins')
) AS v(nome, uf)
JOIN estados e ON e.estado = v.uf
WHERE NOT EXISTS (
    SELECT 1 FROM cidade c WHERE c.cidade = v.nome AND c.estado_id = e.id
);
